"""initial schema

Revision ID: 62bc01c53e8c
Revises:
Create Date: 2026-10-03 14:58:10.140223
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "62bc01c53e8c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("bank", sa.Text(), nullable=False),
        sa.Column("iban", sa.String(length=34), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("account_type", sa.Text(), nullable=False),
        sa.Column("parser_format", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iban"),
    )
    op.create_table(
        "categories",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("parent_slug", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('expense', 'income', 'transfer', 'savings')", name="kind_valid"
        ),
        sa.CheckConstraint(
            "(parent_slug IS NULL) = (kind IS NOT NULL)", name="kind_top_level_only"
        ),
        sa.ForeignKeyConstraint(
            ["parent_slug"],
            ["categories.slug"],
        ),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_table(
        "imports",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("new_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicate_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rule_matched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("llm_matched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("uncategorized_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name="status_valid"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_hash"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("import_id", sa.BigInteger(), nullable=False),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("counterparty_raw", sa.Text(), nullable=False),
        sa.Column("counterparty_normalized", sa.Text(), nullable=False),
        sa.Column("counterparty_iban", sa.String(length=34), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("raw_row", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("category_slug", sa.Text(), nullable=True),
        sa.Column("category_source", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "category_source IN ('rule', 'llm', 'manual')", name="category_source_valid"
        ),
        sa.CheckConstraint(
            "(category_slug IS NULL) = (category_source IS NULL)", name="category_with_source"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_slug"],
            ["categories.slug"],
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "fingerprint", name="uq_transactions_account_fingerprint"
        ),
    )
    op.create_table(
        "categorization_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), nullable=False),
        sa.Column("category_slug", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=True),
        sa.Column("rules_hash", sa.String(length=64), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source IN ('rule', 'llm', 'manual')", name="source_valid"),
        sa.ForeignKeyConstraint(
            ["category_slug"],
            ["categories.slug"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("categorization_events")
    op.drop_table("transactions")
    op.drop_table("imports")
    op.drop_table("categories")
    op.drop_table("accounts")
    # ### end Alembic commands ###
